source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '9.2'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Courir' do
  pod 'Coulomb', :git => 'https://github.com/LesCoureurs/Coulomb.git', :tag => '1.0.2.1'
  pod 'SwiftyGif'
end

target 'CourirTests' do

end

