source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '8.1'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Courir' do
  pod 'Coulomb', :git => 'https://github.com/SplooshKit/Coulomb.git', :tag => '0.0.4'
end

target 'CourirTests' do

end

